name: Builder

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pyinstaller-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019, macos-latest, macos-12, ubuntu-latest]
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.12'
          spec: 'app.py'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'keuzevakken-${{ matrix.os }}'
          options: --onefile, --name "keuzevakken", --windowed,