# Based on https://github.com/felix-seifert/python-pyinstaller-multiple-os-release/blob/main/.github/workflows/release.yaml
name: Release

on:
  push:
    tags:
      - 'v*'  # Push events with tags 'v*', i.e. 'v1.0.4' or 'v0.3.2'

jobs:

  # TODO python tests, see python-pyinstaller-multiple-os-release

  create_release:
    name: Create empty release with tag name to later publish build artifacts via URL
    # needs: unit_test
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Create empty release with tag name
        id: create_empty_release
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
      - name: Copy release URL for later uploads
        run: |
          echo "${{ steps.create_empty_release.outputs.upload_url }}" > release_url.txt
      - name: Save release URL for later uploads
        uses: actions/upload-artifact@v4
        with:
          name: release_url
          path: release_url.txt

  build_and_publish:
    name: 'Build and release for ${{ matrix.TARGET }}'
    permissions:
      contents: write
    needs: create_release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            TARGET: linux-amd64
            PYINSTALLER_OPTIONS: '--onefile, --name "keuzevakken", --windowed'
          - os: windows-latest
            TARGET: windows
            PYINSTALLER_OPTIONS: '--onefile, --name "keuzevakken", --windowed'
          - os: macos-13-xlarge
            TARGET: macos-arm64
            PYINSTALLER_OPTIONS: '--name "keuzevakken", --windowed'
          - os: macos-13
            TARGET: macos-intel
            PYINSTALLER_OPTIONS: '--name "keuzevakken", --windowed'

    steps:
      - uses: actions/checkout@v4

      - name: Create Executable
        uses: ./.github/actions/pyinstaller
        with:
          python_ver: '3.12'
          spec: 'app.py'
          requirements: 'requirements.txt'
          options: '${{ matrix.PYINSTALLER_OPTIONS }}'

      - name: List dist contents
        shell: bash
        run: |
          ls -l ./dist

      - name: Package
        shell: bash
        run: python ".github/workflows/src/package.py"

      - name: List dist contents after package
        shell: bash
        run: |
          ls -l ./dist

      - name: Load previously uploaded release URL
        uses: actions/download-artifact@v4
        with:
          name: release_url

      - name: Get release URL
        id: get_release_details
        shell: bash
        run: |
          url=`cat release_url.txt`
          echo ::set-output name=upload_url::$url

      - name: Publish release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release_details.outputs.upload_url }}
          asset_name: keuzevakken-${{ matrix.TARGET }}.zip
          asset_path: ./dist/keuzevakken.zip
          asset_content_type: application/zip
